name: Build danser

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Danser version'
        type: string
        required: true
      draft:
        description: 'Create draft release'
        type: boolean
        required: false
        default: true

jobs:
  build_windows:
    name: Building windows version
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4

      - name: Install winlibs
        uses: bwoodsend/setup-winlibs-action@v1

      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'
          cache: true

      - name: Build danser
        run: |
          version="${{ github.event.inputs.version }}"

          ./dist-win.sh $version

          if [ ! -f "dist/artifacts/danser-${version// /-s}-win.zip" ]; then
            echo "Danser failed to build"
            exit 1
          fi
        id: build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ !failure() && steps.build.conclusion != 'failure' }}
        with:
          name: danser-${{ runner.os }}
          path: dist/artifacts/*

  build_linux:
    name: Building linux version
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4

      - name: Install needed packages
        run: |
          sudo apt-get update
          sudo apt-get install xorg-dev libgl1-mesa-dev libgtk-3-dev

      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'
          cache: true

      - name: Build danser
        run: |
          version="${{ github.event.inputs.version }}"
          
          chmod +x dist-linux.sh
          ./dist-linux.sh $version
          
          if [ ! -f "dist/artifacts/danser-${version// /-s}-linux.zip" ]; then
            echo "Danser failed to build"
            exit 1
          fi
        id: build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ !failure() && steps.build.conclusion != 'failure' }}
        with:
          name: danser-${{ runner.os }}
          path: dist/artifacts/*

  publish_release:
    name: Publish draft release
    if: ${{ !cancelled() && needs.build_windows.result == 'success' && needs.build_linux.result == 'success' && github.event.inputs.draft }}
    needs: [build_windows, build_linux]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts (Windows)
        uses: actions/download-artifact@v4
        with:
          name: danser-Windows
          path: artifacts

      - name: Download artifacts (Linux)
        uses: actions/download-artifact@v4
        with:
          name: danser-Linux
          path: artifacts

      - name: Create release
        id: create_release
        run: |
          set -xe
          shopt -s nullglob

          version="${{ github.event.inputs.version }}"

          NAME="${version// / snapshot }"
          TAGNAME="${version// /-s}"

          gh release create "$TAGNAME" --draft -t "$NAME" --target "master" $(for a in artifacts/*.{zip,tar.xz}; do echo $a; done)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
